### ISSUE TITLE
package name issue?

### ISSUE THREAD

**Issue by tylerandrewscott** [Clarivate-SAR/woslite_r_client#2]
Hello,
   When I try to install the package, this error occurs:

### 
**> Sys.info()**
                                sysname                                 release
                                "Linux"                 "4.19.0-16-cloud-amd64"
                                version                                nodename
"#1 SMP Debian 4.19.181-1 (2021-03-19)"                    "rstudio-premptible"
                                machine                                   login
                               "x86_64"                               "unknown"
                                   user                          effective_user
                               "master"                                "master"

**> library(devtools)**

**> install_github("Clarivate-SAR/woslite_r_client")**
Downloading GitHub repo Clarivate-SAR/woslite_r_client@HEAD
✓  checking for file ‘/private/var/folders/n_/4b1w6nqd5gdgtmmlrm6pm82c0000gn/T/RtmpDQiA1l/remotes61fe76b20b5b/Clarivate-SAR-woslite_r_client-713b51a/DESCRIPTION’ ...
─  preparing ‘woslite_r_client’:
E  checking DESCRIPTION meta-information ...
   Malformed package name
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
   
Error: Failed to install 'woslite_r_client' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr:
E> * checking for file ‘/tmp/RtmpYnEfPx/remotes11023944e2f8/Clarivate-SAR-woslite_r_client-713b51a/DESCRIPTION’ ... OK
E> * preparing ‘woslite_r_client’:
E> * checking DESCRIPTION meta-information ... ERROR
E> Malformed package name
E> 
E> See section 'The DESCRIPTION file' in the 'Writing R Extensions'
E> m

**Comment by arecibo** [comment]
> Hello,
> When I try to install the package, this error occurs:
> 
> **> Sys.info()**
> sysname release
> "Linux" "4.19.0-16-cloud-amd64"
> version nodename
> "#1 SMP Debian 4.19.181-1 (2021-03-19)" "rstudio-premptible"
> machine login
> "x86_64" "unknown"
> user effective_user
> "master" "master"
> 
> **> library(devtools)**
> 
> **> install_github("Clarivate-SAR/woslite_r_client")**
> Downloading GitHub repo Clarivate-SAR/woslite_r_client@HEAD
> ✓ checking for file ‘/private/var/folders/n_/4b1w6nqd5gdgtmmlrm6pm82c0000gn/T/RtmpDQiA1l/remotes61fe76b20b5b/Clarivate-SAR-woslite_r_client-713b51a/DESCRIPTION’ ...
> ─ preparing ‘woslite_r_client’:
> E checking DESCRIPTION meta-information ...
> Malformed package name
> 
> See section 'The DESCRIPTION file' in the 'Writing R Extensions'
> manual.
> 
> Error: Failed to install 'woslite_r_client' from GitHub:
> System command 'R' failed, exit status: 1, stdout + stderr:
> E> * checking for file ‘/tmp/RtmpYnEfPx/remotes11023944e2f8/Clarivate-SAR-woslite_r_client-713b51a/DESCRIPTION’ ... OK
> E> * preparing ‘woslite_r_client’:
> E> * checking DESCRIPTION meta-information ... ERROR
> E> Malformed package name
> E>
> E> See section 'The DESCRIPTION file' in the 'Writing R Extensions'
> E> m

Same error on OSX 11.4 and R 4.1.0.

**Comment by iangow** [comment]
I get the same issue. I will submit a pull request.

**Comment by maloku** [comment]
@iangow merged your PR. 

@tylerascott and @arecibo can you please confirm that this is working for you? Please create a new issue in case you experience other problems.
